version: '3.1'

services:
  mailwizz:
    build: ./mailwizz
    restart: unless-stopped
    volumes:
      - ./mailwizz/latest:/var/www/html:rw
    environment:
      TZ: 'Europe/Amsterdam'
    depends_on:
      - mariadb
    networks:
      - mailwizz-db
      - nginx-proxy-manager

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'B6n5mR51zsj4SubPWbMyitsZ'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz_user'
      MYSQL_PASSWORD: 'wtTCVFjC50as50im1UTcJB3ws'
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - mailwizz-db


networks:
  nginx-proxy-manager:
    external: true
  mailwizz-db:
    external: false
    driver: bridge