version: '3.1'

services:
  mailwizz:
    build: ./mailwizz
    restart: unless-stopped
    volumes:
      - ./mailwizz/latest:/var/www/html:rw
    environment:
      TZ: 'Europe/Kiev'
    depends_on:
      - mariadb
    networks:
      - mailwizz-db
      - nginx-proxy-manager

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mailwizz'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz'
      MYSQL_PASSWORD: 'mailwizz'
    volumes:
      - nginx-pm-db_mysql:/var/lib/mysql
    networks:
      - mailwizz-db

volumes:
  nginx-pm-db_mysql:

networks:
  nginx-proxy-manager:
    external: true
  mailwizz-db:
    external: false
    driver: bridge