version: '3.1'

services:
  mailwizz:
    build: ./mailwizz
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /data/mailwizz/data/latest:/var/www/html:rw
    environment:
      TZ: 'Europe/Amsterdam'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'd>WCBiodeUm8&:2R8po^8'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz_user'
      MYSQL_PASSWORD: 'ng8}H)qm!9|Qdy7TB<n20'
    volumes:
      - /data/mailwizz/mysql:/var/lib/mysql
