services:
  mailwizz:
    container_name: mailwizz
    build: ./mailwizz
    restart: unless-stopped
    volumes:
      - /data/mailwizz/app:/var/www/html:rw
    environment:
      TZ: 'Europe/Amsterdam'
    depends_on:
      - mariadb
    networks:
      - nginx-proxy-manager
      - mailwizz-db


  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'd>WCBiodeUm8&:2R8po^8'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz_user'
      MYSQL_PASSWORD: 'ng8}H)qm!9|Qdy7TB<n20'
    volumes:
      - /data/mailwizz/db:/var/lib/mysql
    networks:
      - mailwizz-db

networks:
  nginx-proxy-manager:
    external: true
  mailwizz-db:
    external: false