version: '3.1'

services:
  mailwizz:
    build: ./mailwizz
    restart: unless-stopped
    volumes:
      - mw-data:/var/www/html:rw
    environment:
      TZ: 'Europe/Amsterdam'
    depends_on:
      - mariadb
    networks:
      - mailwizz-db
      - nginx-proxy-manager

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'B6n5mR51zsj4SubPWbMyitsZ'
      MYSQL_DATABASE: 'mailwizz'
      MYSQL_USER: 'mailwizz_user'
      MYSQL_PASSWORD: 'wtTCVFjC50as50im1UTcJB3ws'
    volumes:
      - nginx-pm-db_mysql:/var/lib/mysql
    networks:
      - mailwizz-db

volumes:
  nginx-pm-db_mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mailwizz/database
  mw-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/mailwizz/app_data

networks:
  nginx-proxy-manager:
    external: true
  mailwizz-db:
    external: false
    driver: bridge